// seedUser.js
// =============================================================================
// Injects a single test user into Postgres whose UUID matches the JWT payload
// generated by generateToken.js. Run once before testing the /nearby endpoint.
//
// IMPORTANT: Prisma field names are camelCase (matching schema.prisma), not the
// snake_case DB column names. Using snake_case here would throw:
//   "Unknown argument `display_name`"
// =============================================================================

import prisma from './prisma.js';

const TEST_USER_ID = '123e4567-e89b-12d3-a456-426614174000';

async function main() {
  console.log('\n[seedUser] Seeding/updating test user...');

  // Prisma field names must match schema.prisma model field names (camelCase)
  const user = await prisma.user.upsert({
    where: { id: TEST_USER_ID },
    update: {
      role: 'admin',
    },
    create: {
      id:           TEST_USER_ID,          // @id — must match JWT sub claim
      displayName:  'Test User',           // maps to display_name column
      emailHash:    'a'.repeat(64),        // @unique SHA-256 hex (64 chars); dummy value
      passwordHash: '$2b$10$placeholder',  // bcrypt-shaped dummy; never used for login
      role:         'admin',               // UserRole enum
      locale:       'en-IN',              // stored as varchar(10)
    },
  });

  console.log(`\n╔═══════════════════════════════════════════════════╗`);
  console.log(`║          USER SEEDED/UPDATED SUCCESSFULLY         ║`);
  console.log(`╚═══════════════════════════════════════════════════╝`);
  console.log(`  id:     ${user.id}`);
  console.log(`  name:   ${user.displayName}`);
  console.log(`  role:   ${user.role}`);
  console.log(`  locale: ${user.locale}`);
  console.log(`\n  ✅  JWT sub claim matches DB id — auth will pass.\n`);
}

main()
  .catch((err) => {
    console.error('\n[seedUser] ❌  Failed to seed user:', err.message);
    // Surface useful Prisma-specific hints
    if (err.code === 'P2002') {
      console.error('  → Unique constraint violated. emailHash already exists.');
    }
    if (err.code === 'P1001') {
      console.error('  → Cannot reach Postgres. Is the DB container running?');
      console.error('    Run: docker-compose up -d  (from the Ummah root folder)');
    }
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
